// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrwniheDvmxkoNNG9oCtHviAKUBKnKEI',
    appId: '1:860643165978:web:2ad378dd835724f6078ea3',
    messagingSenderId: '860643165978',
    projectId: 'fir-tutorial-8db47',
    authDomain: 'fir-tutorial-8db47.firebaseapp.com',
    storageBucket: 'fir-tutorial-8db47.appspot.com',
    measurementId: 'G-13DF71ZVB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-b_S8k_iLXGljVrI83Z-cqB2ChSLrdQc',
    appId: '1:860643165978:android:3f54b86b0760bc05078ea3',
    messagingSenderId: '860643165978',
    projectId: 'fir-tutorial-8db47',
    storageBucket: 'fir-tutorial-8db47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDsZPImGAEdnPVBzKq29aToBz5P4G9_Tg',
    appId: '1:860643165978:ios:d964d298e1950733078ea3',
    messagingSenderId: '860643165978',
    projectId: 'fir-tutorial-8db47',
    storageBucket: 'fir-tutorial-8db47.appspot.com',
    iosClientId: '860643165978-huqhq2h69f4a685r3sm1oc3aulmmubd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
